model:
  method: backward
  n_hidden: 128
  n_layer: 3
  act: F.relu
  dropout: 0.3
  norm_info: ~
  input_layer: false
  output_layer: false

training:
  lr: 5e-3
  weight_decay: 5e-3
  n_pre_epochs: 200
  n_epochs: 200
  patience: ~
  criterion: metric

dataset:
  sparse: true

analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false